// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RealityScraper.Infrastructure.Contexts;

#nullable disable

namespace RealityScraper.Infrastructure.Database.Migrations
{
    [DbContext(typeof(RealityDbContext))]
    [Migration("20260314203557_UpdateSnapshotForDateTimeOffset")]
    partial class UpdateSnapshotForDateTimeOffset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RealityScraper.Domain.Entities.Realty.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("PriceFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ScraperTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ScraperTaskId");

                    b.HasIndex("ExternalId", "ScraperTaskId")
                        .IsUnique();

                    b.ToTable("Listing");
                });

            modelBuilder.Entity("RealityScraper.Domain.Entities.Realty.PriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.ToTable("PriceHistory");
                });

            modelBuilder.Entity("RealityScraper.Domain.Entities.Tasks.ScraperTaskRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ScraperTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ScraperTaskId");

                    b.ToTable("ScraperTaskRecipient");
                });

            modelBuilder.Entity("RealityScraper.Domain.Entities.Tasks.ScraperTaskTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScraperTaskId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScraperType")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ScraperTaskId");

                    b.ToTable("ScraperTaskTarget");
                });

            modelBuilder.Entity("RealityScraper.Domain.Entities.Tasks.TaskBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("NextRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tasks", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("TaskBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RealityScraper.Domain.Entities.Tasks.ScraperTask", b =>
                {
                    b.HasBaseType("RealityScraper.Domain.Entities.Tasks.TaskBase");

                    b.HasDiscriminator().HasValue("ScraperTask");
                });

            modelBuilder.Entity("RealityScraper.Domain.Entities.Realty.Listing", b =>
                {
                    b.HasOne("RealityScraper.Domain.Entities.Tasks.ScraperTask", null)
                        .WithMany()
                        .HasForeignKey("ScraperTaskId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RealityScraper.Domain.Entities.Realty.PriceHistory", b =>
                {
                    b.HasOne("RealityScraper.Domain.Entities.Realty.Listing", "Listing")
                        .WithMany("PriceHistories")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("RealityScraper.Domain.Entities.Tasks.ScraperTaskRecipient", b =>
                {
                    b.HasOne("RealityScraper.Domain.Entities.Tasks.ScraperTask", "ScraperTask")
                        .WithMany("Recipients")
                        .HasForeignKey("ScraperTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScraperTask");
                });

            modelBuilder.Entity("RealityScraper.Domain.Entities.Tasks.ScraperTaskTarget", b =>
                {
                    b.HasOne("RealityScraper.Domain.Entities.Tasks.ScraperTask", "ScraperTask")
                        .WithMany("Targets")
                        .HasForeignKey("ScraperTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScraperTask");
                });

            modelBuilder.Entity("RealityScraper.Domain.Entities.Realty.Listing", b =>
                {
                    b.Navigation("PriceHistories");
                });

            modelBuilder.Entity("RealityScraper.Domain.Entities.Tasks.ScraperTask", b =>
                {
                    b.Navigation("Recipients");

                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
